// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using stok_takip.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260803075122_AddAuthorizationPolicies")]
    partial class AddAuthorizationPolicies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("stok_takip.Models.AppAuthorizationPolicy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("key");

                    b.Property<int>("PermitLimit")
                        .HasColumnType("int")
                        .HasColumnName("permit_limit");

                    b.Property<int>("WindowSeconds")
                        .HasColumnType("int")
                        .HasColumnName("window_seconds");

                    b.HasKey("Id")
                        .HasName("pk_app_authorization_policies");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_app_authorization_policies_key");

                    b.ToTable("app_authorization_policies");
                });

            modelBuilder.Entity("stok_takip.Models.AppPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("module");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_app_permissions");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_app_permissions_name");

                    b.ToTable("app_permissions");
                });

            modelBuilder.Entity("stok_takip.Models.AppPolicyPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("permission_id");

                    b.Property<int>("PolicyId")
                        .HasColumnType("int")
                        .HasColumnName("policy_id");

                    b.HasKey("Id")
                        .HasName("pk_app_policy_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_app_policy_permissions_permission_id");

                    b.HasIndex("PolicyId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("ix_app_policy_permissions_policy_id_permission_id");

                    b.ToTable("app_policy_permissions");
                });

            modelBuilder.Entity("stok_takip.Models.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit")
                        .HasColumnName("is_system_role");

                    b.Property<int>("Level")
                        .HasColumnType("int")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_app_roles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_app_roles_name");

                    b.ToTable("app_roles");
                });

            modelBuilder.Entity("stok_takip.Models.AppRolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int")
                        .HasColumnName("permission_id");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_app_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_app_role_permissions_permission_id");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("ix_app_role_permissions_role_id_permission_id");

                    b.ToTable("app_role_permissions");
                });

            modelBuilder.Entity("stok_takip.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssignedToId")
                        .HasColumnType("int")
                        .HasColumnName("assigned_to_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("NextMaintenanceDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("next_maintenance_date");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("serial_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_assets");

                    b.HasIndex("AssignedToId")
                        .HasDatabaseName("ix_assets_assigned_to_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_assets_product_id");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_assets_serial_number")
                        .HasFilter("[is_deleted] = 0");

                    b.ToTable("assets");
                });

            modelBuilder.Entity("stok_takip.Models.AssetHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int")
                        .HasColumnName("asset_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("event_type");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asset_histories");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_asset_histories_asset_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asset_histories_user_id");

                    b.ToTable("asset_histories");
                });

            modelBuilder.Entity("stok_takip.Models.AttributeRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllowedValues")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("allowed_values");

                    b.Property<string>("AttributeKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("attribute_key");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("data_type");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int")
                        .HasColumnName("display_order");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit")
                        .HasColumnName("is_required");

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("max_value");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("min_value");

                    b.Property<string>("TargetLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("target_level");

                    b.Property<string>("UiComponent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ui_component");

                    b.HasKey("Id")
                        .HasName("pk_attribute_rules");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_attribute_rules_category_id");

                    b.ToTable("attribute_rules");
                });

            modelBuilder.Entity("stok_takip.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_categories_parent_id");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("stok_takip.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_locations_code");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("ix_locations_warehouse_id");

                    b.ToTable("locations");
                });

            modelBuilder.Entity("stok_takip.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("severity");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("stok_takip.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Attributes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("attributes");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("barcode");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cost");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<int>("MinStockLevel")
                        .HasColumnType("int")
                        .HasColumnName("min_stock_level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasDatabaseName("ix_products_barcode")
                        .HasFilter("[is_deleted] = 0");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_products_category_id");

                    b.ToTable("products");
                });

            modelBuilder.Entity("stok_takip.Models.ProductSupplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsPreferred")
                        .HasColumnType("bit")
                        .HasColumnName("is_preferred");

                    b.Property<int?>("LeadTimeDays")
                        .HasColumnType("int")
                        .HasColumnName("lead_time_days");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<decimal?>("PurchasePrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("purchase_price");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("supplier_id");

                    b.Property<string>("SupplierProductCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("supplier_product_code");

                    b.HasKey("Id")
                        .HasName("pk_product_suppliers");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_product_suppliers_supplier_id");

                    b.HasIndex("ProductId", "SupplierId")
                        .IsUnique()
                        .HasDatabaseName("ix_product_suppliers_product_id_supplier_id")
                        .HasFilter("[is_deleted] = 0");

                    b.ToTable("product_suppliers");
                });

            modelBuilder.Entity("stok_takip.Models.SecurityAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("action_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("entity_name");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("NewValues")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("new_values");

                    b.Property<string>("OldValues")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_values");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_security_audit_logs");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_security_audit_logs_user_id");

                    b.ToTable("security_audit_logs");
                });

            modelBuilder.Entity("stok_takip.Models.StockLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("location_id");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.HasKey("Id")
                        .HasName("pk_stock_levels");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ix_stock_levels_location_id");

                    b.HasIndex("ProductId", "LocationId")
                        .IsUnique()
                        .HasDatabaseName("ix_stock_levels_product_id_location_id");

                    b.ToTable("stock_levels");
                });

            modelBuilder.Entity("stok_takip.Models.StockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Destination")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("destination");

                    b.Property<string>("DocumentNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("document_number");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("movement_type");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int?>("SourceLocationId")
                        .HasColumnType("int")
                        .HasColumnName("source_location_id");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("supplier_id");

                    b.Property<string>("SupplierName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("supplier_name");

                    b.Property<string>("SupplierTaxNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("supplier_tax_number");

                    b.Property<int?>("TargetLocationId")
                        .HasColumnType("int")
                        .HasColumnName("target_location_id");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_price");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_stock_movements");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_stock_movements_product_id");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_stock_movements_supplier_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_stock_movements_user_id");

                    b.ToTable("stock_movements");
                });

            modelBuilder.Entity("stok_takip.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("contact_name");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("TaxNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tax_number");

                    b.HasKey("Id")
                        .HasName("pk_suppliers");

                    b.ToTable("suppliers");
                });

            modelBuilder.Entity("stok_takip.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ConfirmationCodeExpiry")
                        .HasColumnType("datetime2")
                        .HasColumnName("confirmation_code_expiry");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("email");

                    b.Property<string>("EmailConfirmationCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email_confirmation_code");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("int")
                        .HasColumnName("failed_login_attempts");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("is_email_confirmed");

                    b.Property<DateTime?>("LastFailedLoginAttempt")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_failed_login_attempt");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordResetCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_reset_code");

                    b.Property<DateTime?>("PasswordResetCodeExpiry")
                        .HasColumnType("datetime2")
                        .HasColumnName("password_reset_code_expiry");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone_number");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_users_role_id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("stok_takip.Models.UserSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("DeviceBrowser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("device_browser");

                    b.Property<string>("DeviceOs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("device_os");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ip_address");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("SessionToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("session_token");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_sessions");

                    b.HasIndex("SessionToken")
                        .IsUnique()
                        .HasDatabaseName("ix_user_sessions_session_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_sessions_user_id");

                    b.ToTable("user_sessions");
                });

            modelBuilder.Entity("stok_takip.Models.UserWarehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int?>("WarehouseId")
                        .HasColumnType("int")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_user_warehouse");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_warehouse_user_id");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("ix_user_warehouse_warehouse_id");

                    b.ToTable("user_warehouse");
                });

            modelBuilder.Entity("stok_takip.Models.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_warehouses");

                    b.ToTable("warehouses");
                });

            modelBuilder.Entity("stok_takip.Models.AppPolicyPermission", b =>
                {
                    b.HasOne("stok_takip.Models.AppPermission", "Permission")
                        .WithMany("PolicyPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_app_policy_permissions_app_permissions_permission_id");

                    b.HasOne("stok_takip.Models.AppAuthorizationPolicy", "Policy")
                        .WithMany("PolicyPermissions")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_app_policy_permissions_app_authorization_policies_policy_id");

                    b.Navigation("Permission");

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("stok_takip.Models.AppRolePermission", b =>
                {
                    b.HasOne("stok_takip.Models.AppPermission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_app_role_permissions_app_permissions_permission_id");

                    b.HasOne("stok_takip.Models.AppRole", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_app_role_permissions_app_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("stok_takip.Models.Asset", b =>
                {
                    b.HasOne("stok_takip.Models.User", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId")
                        .HasConstraintName("fk_assets_users_assigned_to_id");

                    b.HasOne("stok_takip.Models.Product", "Product")
                        .WithMany("Assets")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assets_products_product_id");

                    b.Navigation("AssignedTo");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("stok_takip.Models.AssetHistory", b =>
                {
                    b.HasOne("stok_takip.Models.Asset", "Asset")
                        .WithMany("History")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_asset_histories_assets_asset_id");

                    b.HasOne("stok_takip.Models.User", "User")
                        .WithMany("AssetHistories")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_asset_histories_users_user_id");

                    b.Navigation("Asset");

                    b.Navigation("User");
                });

            modelBuilder.Entity("stok_takip.Models.AttributeRule", b =>
                {
                    b.HasOne("stok_takip.Models.Category", "Category")
                        .WithMany("AttributeRules")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_attribute_rules_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("stok_takip.Models.Category", b =>
                {
                    b.HasOne("stok_takip.Models.Category", "Parent")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categories_categories_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("stok_takip.Models.Location", b =>
                {
                    b.HasOne("stok_takip.Models.Warehouse", "Warehouse")
                        .WithMany("Locations")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_locations_warehouses_warehouse_id");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("stok_takip.Models.Product", b =>
                {
                    b.HasOne("stok_takip.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_products_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("stok_takip.Models.ProductSupplier", b =>
                {
                    b.HasOne("stok_takip.Models.Product", "Product")
                        .WithMany("ProductSuppliers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_suppliers_products_product_id");

                    b.HasOne("stok_takip.Models.Supplier", "Supplier")
                        .WithMany("ProductSuppliers")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_product_suppliers_suppliers_supplier_id");

                    b.Navigation("Product");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("stok_takip.Models.SecurityAuditLog", b =>
                {
                    b.HasOne("stok_takip.Models.User", "User")
                        .WithMany("SecurityAuditLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_security_audit_logs_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("stok_takip.Models.StockLevel", b =>
                {
                    b.HasOne("stok_takip.Models.Location", "Location")
                        .WithMany("StockLevels")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stock_levels_locations_location_id");

                    b.HasOne("stok_takip.Models.Product", "Product")
                        .WithMany("StockLevels")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stock_levels_products_product_id");

                    b.Navigation("Location");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("stok_takip.Models.StockMovement", b =>
                {
                    b.HasOne("stok_takip.Models.Product", "Product")
                        .WithMany("StockMovements")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_stock_movements_products_product_id");

                    b.HasOne("stok_takip.Models.Supplier", "Supplier")
                        .WithMany("StockMovements")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_stock_movements_suppliers_supplier_id");

                    b.HasOne("stok_takip.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_stock_movements_users_user_id");

                    b.Navigation("Product");

                    b.Navigation("Supplier");

                    b.Navigation("User");
                });

            modelBuilder.Entity("stok_takip.Models.User", b =>
                {
                    b.HasOne("stok_takip.Models.AppRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_app_roles_role_id");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("stok_takip.Models.UserSession", b =>
                {
                    b.HasOne("stok_takip.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_sessions_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("stok_takip.Models.UserWarehouse", b =>
                {
                    b.HasOne("stok_takip.Models.User", null)
                        .WithMany("UserWarehouses")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_user_warehouse_users_user_id");

                    b.HasOne("stok_takip.Models.Warehouse", null)
                        .WithMany("UserWarehouses")
                        .HasForeignKey("WarehouseId")
                        .HasConstraintName("fk_user_warehouse_warehouses_warehouse_id");
                });

            modelBuilder.Entity("stok_takip.Models.AppAuthorizationPolicy", b =>
                {
                    b.Navigation("PolicyPermissions");
                });

            modelBuilder.Entity("stok_takip.Models.AppPermission", b =>
                {
                    b.Navigation("PolicyPermissions");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("stok_takip.Models.AppRole", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("stok_takip.Models.Asset", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("stok_takip.Models.Category", b =>
                {
                    b.Navigation("AttributeRules");

                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("stok_takip.Models.Location", b =>
                {
                    b.Navigation("StockLevels");
                });

            modelBuilder.Entity("stok_takip.Models.Product", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("ProductSuppliers");

                    b.Navigation("StockLevels");

                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("stok_takip.Models.Supplier", b =>
                {
                    b.Navigation("ProductSuppliers");

                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("stok_takip.Models.User", b =>
                {
                    b.Navigation("AssetHistories");

                    b.Navigation("SecurityAuditLogs");

                    b.Navigation("UserWarehouses");
                });

            modelBuilder.Entity("stok_takip.Models.Warehouse", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("UserWarehouses");
                });
#pragma warning restore 612, 618
        }
    }
}
