// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using stok_takip.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("stok_takip.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ıd");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_ıd");

                    b.HasKey("Id")
                        .HasName("pk_asset");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ıx_asset_product_ıd");

                    b.ToTable("asset");
                });

            modelBuilder.Entity("stok_takip.Models.AssetHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ıd");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_ıd");

                    b.HasKey("Id")
                        .HasName("pk_asset_history");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ıx_asset_history_user_ıd");

                    b.ToTable("asset_history");
                });

            modelBuilder.Entity("stok_takip.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ıd");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_ıd");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ıx_categories_parent_ıd");

                    b.ToTable("categories");
                });

            modelBuilder.Entity("stok_takip.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ıd");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("int")
                        .HasColumnName("warehouse_ıd");

                    b.HasKey("Id")
                        .HasName("pk_locations");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ıx_locations_code");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("ıx_locations_warehouse_ıd");

                    b.ToTable("locations");
                });

            modelBuilder.Entity("stok_takip.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ıd");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("ıs_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("stok_takip.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ıd");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("barcode");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_ıd");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("MinStockLevel")
                        .HasColumnType("int")
                        .HasColumnName("min_stock_level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("Barcode")
                        .IsUnique()
                        .HasDatabaseName("ıx_products_barcode");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ıx_products_category_ıd");

                    b.ToTable("products");
                });

            modelBuilder.Entity("stok_takip.Models.SecurityAuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ıd");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_ıd");

                    b.HasKey("Id")
                        .HasName("pk_security_audit_log");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ıx_security_audit_log_user_ıd");

                    b.ToTable("security_audit_log");
                });

            modelBuilder.Entity("stok_takip.Models.StockLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ıd");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("LocationId")
                        .HasColumnType("int")
                        .HasColumnName("location_ıd");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_ıd");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_stock_levels");

                    b.HasIndex("LocationId")
                        .HasDatabaseName("ıx_stock_levels_location_ıd");

                    b.HasIndex("ProductId", "LocationId")
                        .IsUnique()
                        .HasDatabaseName("ıx_stock_levels_product_ıd_location_ıd");

                    b.ToTable("stock_levels");
                });

            modelBuilder.Entity("stok_takip.Models.StockMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ıd");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("MovementType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("movement_type");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_ıd");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("Id")
                        .HasName("pk_stock_movements");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ıx_stock_movements_product_ıd");

                    b.ToTable("stock_movements");
                });

            modelBuilder.Entity("stok_takip.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ıd");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ıx_users_email");

                    b.ToTable("users");
                });

            modelBuilder.Entity("stok_takip.Models.UserWarehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ıd");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_ıd");

                    b.Property<int?>("WarehouseId")
                        .HasColumnType("int")
                        .HasColumnName("warehouse_ıd");

                    b.HasKey("Id")
                        .HasName("pk_user_warehouse");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ıx_user_warehouse_user_ıd");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("ıx_user_warehouse_warehouse_ıd");

                    b.ToTable("user_warehouse");
                });

            modelBuilder.Entity("stok_takip.Models.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ıd");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_warehouses");

                    b.ToTable("warehouses");
                });

            modelBuilder.Entity("stok_takip.Models.Asset", b =>
                {
                    b.HasOne("stok_takip.Models.Product", null)
                        .WithMany("Assets")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("fk_asset_products_product_ıd");
                });

            modelBuilder.Entity("stok_takip.Models.AssetHistory", b =>
                {
                    b.HasOne("stok_takip.Models.User", null)
                        .WithMany("AssetHistories")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_asset_history_users_user_ıd");
                });

            modelBuilder.Entity("stok_takip.Models.Category", b =>
                {
                    b.HasOne("stok_takip.Models.Category", "Parent")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categories_categories_parent_ıd");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("stok_takip.Models.Location", b =>
                {
                    b.HasOne("stok_takip.Models.Warehouse", "Warehouse")
                        .WithMany("Locations")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_locations_warehouses_warehouse_ıd");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("stok_takip.Models.Product", b =>
                {
                    b.HasOne("stok_takip.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_products_categories_category_ıd");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("stok_takip.Models.SecurityAuditLog", b =>
                {
                    b.HasOne("stok_takip.Models.User", null)
                        .WithMany("SecurityAuditLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_security_audit_log_users_user_ıd");
                });

            modelBuilder.Entity("stok_takip.Models.StockLevel", b =>
                {
                    b.HasOne("stok_takip.Models.Location", "Location")
                        .WithMany("StockLevels")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stock_levels_locations_location_ıd");

                    b.HasOne("stok_takip.Models.Product", "Product")
                        .WithMany("StockLevels")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stock_levels_products_product_ıd");

                    b.Navigation("Location");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("stok_takip.Models.StockMovement", b =>
                {
                    b.HasOne("stok_takip.Models.Product", "Product")
                        .WithMany("StockMovements")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stock_movements_products_product_ıd");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("stok_takip.Models.UserWarehouse", b =>
                {
                    b.HasOne("stok_takip.Models.User", null)
                        .WithMany("UserWarehouses")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_user_warehouse_users_user_ıd");

                    b.HasOne("stok_takip.Models.Warehouse", null)
                        .WithMany("UserWarehouses")
                        .HasForeignKey("WarehouseId")
                        .HasConstraintName("fk_user_warehouse_warehouses_warehouse_ıd");
                });

            modelBuilder.Entity("stok_takip.Models.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("stok_takip.Models.Location", b =>
                {
                    b.Navigation("StockLevels");
                });

            modelBuilder.Entity("stok_takip.Models.Product", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("StockLevels");

                    b.Navigation("StockMovements");
                });

            modelBuilder.Entity("stok_takip.Models.User", b =>
                {
                    b.Navigation("AssetHistories");

                    b.Navigation("SecurityAuditLogs");

                    b.Navigation("UserWarehouses");
                });

            modelBuilder.Entity("stok_takip.Models.Warehouse", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("UserWarehouses");
                });
#pragma warning restore 612, 618
        }
    }
}
