server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;

        # Content Security Policy (CSP) Header
        # Hem Docker (port 5000) hem yerel dotnet run (port 5136) backend portlarına izin verildi.
        # Script (JS) için satır içi (inline) kod çalıştırılması KESİNLİKLE yasaklanmıştır.
        add_header Content-Security-Policy "default-src 'self'; script-src 'self' http://localhost:5136 http://localhost:5000; connect-src 'self' http://localhost:5136 http://localhost:5000; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com https://cdn.jsdelivr.net; img-src 'self' data:;" always;
    }
}
